apiVersion: v1
kind: Service
metadata:
   name: ksi-rsyslog-service
spec:
  selector:
    app: ksi-rsyslog
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 16514
    targetPort: ksi-rsyslog-svc
