apiVersion: v1
kind: PersistentVolume
metadata:
  name: ksi-log-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logksi"
